# Generated by Django 5.0.1 on 2024-01-19 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 15, 24, 1, 991844, tzinfo=datetime.timezone.utc)),
        ),
    ]
