# Generated by Django 4.2.2 on 2024-09-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investment_saving_delete_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='saving',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
